lib/help/key_object.js
lib/help/key_utils.js

This change removes a syntaxError that was being thrown by babel. The
specific error being thrown was "Identifier directly after number".

fix: removes syntax error ("0n" => "0")

---

docs/README.md

Fixing a little typo in JWT.verify method description.

doc: fix typo

---

lib/help/key_utils.js
test/jwk/import.test.js

Only possible to handle when KeyObject API is available in the runtime.
closes #85

fix: handle private EC keys without public component

---

docs/README.md
lib/jwt/verify.js
test/jwt/verify.test.js
types/index.d.ts

JWT.verify can now have an array of possible issuers supplied in the options
I required this for use with google authentication because there are 2 different issuers for google id tokens accounts.google.com and https://accounts.google.com

feat: support for validating issuer from a list of values

---

src/util/errors.ts

This is just to make it possible to get the code, without having to create a new instance of the class.
In our use case, we emit a metric with the error code on some failures. The unit tests look like:
```ts
assert(emittedMetric === new JWTExpired("test message").code);
```
which isn't nearly as clean as:
```ts
assert(emittedMetric === JWTExpired.code);
```
Discussion is [here](https://github.com/panva/jose/discussions/170)

feat: export error codes as static properties

---

package.json
src/jwks/remote.ts
src/runtime/browser/fetch.ts
src/runtime/browser/fetch_jwks.ts
src/runtime/node/fetch_jwks.ts

Here's a tiny fix that should hopefully save a lot of people a lot of headaches.
esbuild (and apparently other bundlers too) when outputting a single JS module (for esbuild, that's in `--format=esm`), everything is concatenated in a single file and de-scoped.
Because jose defines a variable called `fetch`, that overrode the `window.fetch` method, and it was causing all fetch requests in my app to fail.
Took a while to figure out. I was able to find a workaround by switching esbuild to `--format=iife`, which was fine for my app, but if someone needs an output as esm, they are stuck.

fix(browser): avoid global-conflicting variable name fetch

---

package.json
src/jwe/compact/decrypt.ts
src/jwe/flattened/decrypt.ts
src/jwe/general/decrypt.ts
src/jws/compact/verify.ts
src/jws/flattened/verify.ts
src/jws/general/verify.ts
src/jwt/decrypt.ts
src/jwt/unsecured.ts
src/jwt/verify.ts
src/runtime/node/check_modulus_length.ts
src/runtime/node/webcrypto.ts
src/util/decode_protected_header.ts

Exporting type `JWTVerifyResult` from `jose/jwt/verify`
I did not see any way to `import { JWTVerifyResult }` with the existing import maps.  Apologies if this is redundant.
Thank you for a great library!

feat(typescript): export consume module interface types

---

src/jws/flattened/verify.ts
test/jws/flattened.verify.test.mjs

This PR adds additional check in JWS verification allowing for catching malformed JWS protected header. Previously, when user provided token which "appeared" like a well-formed JWS, but in reality protected header could not be `JSON.parse`-d, `SyntaxError` would be thrown. With this PR, `JWSInvalid('JWS Protected Header is invalid')` is thrown.
E.g., having JWT (with `1` prepended):
```
1eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqb3NlLXRlc3QiLCJpYXQiOjE2MjkxMDM1NDksImV4cCI6MTY2MDcyNTk0OSwiYXVkIjoiam9zZS10ZXN0Iiwic3ViIjoiam9zZS10ZXN0In0.FWiGkd6idzmcw9JhmLuoOjtnDXhiOOF0bFuPcw4Nn8Y
```
Previously, when using `jwtVerify`:
```
SyntaxError: Unexpected token i in JSON at position 0
``` 
was thrown. After this PR, `JWSInvalid` error with message `JWS Protected Header is invalid` and can be …

feat: throw custom error when jws protected header is not valid json

---

src/types.d.ts

The b64 header is currently defined as a required field, so omitting it throws a typescript error. Since its type is defined as "never", there is nothing that can be assigned to it, making it impossible to actually use.
This makes b64 optional, which still prevents assigning to it due to the type.

fix(typescript): Make b64 header optional

---

docs/classes/jwt_unsecured.UnsecuredJWT.md
src/jwt/unsecured.ts

`.decode()` is a static function of the `UnsecuredJWT` class. Instantiating a new object and calling the function afterwards doesn't make sense and leads to an exception:
```
const payload = new jose.UnsecuredJWT.decode(unsecuredJwt, {
^
TypeError: jose.UnsecuredJWT.decode is not a constructor
at file:///Users/maxarndt/Downloads/some-repo/utilities/jwt/unsecuredJWT.js:12:17
at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
at async Promise.all (index 0)
at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
at async loadESM (node:internal/process/esm_loader:88:5)
at async handleMainPromise (node:internal/modules/run_main:65:12)
```
Because of this the `new` operator should be removed from the examples.

fix decode example of UnsecuredJWT

---

src/jwe/compact/decrypt.ts
test/jwe/compact.decrypt.test.mjs
test/jwe/flattened.decrypt.test.mjs
test/jwe/general.test.mjs

When encrypting an empty string/buffer in GCM mode, the resulting ciphertext is also empty. Trying to then decrypt this using compact decryption then throws an error because it converts the empty string to undefined and then throws an error.
This is probably an edge case, but it is valid to encrypt and decrypt an empty value. This is also not an issue in CBC mode, since the ciphertext of an empty value is a non-empty value.

Support decrypting empty ciphertext

---

src/jwks/remote.ts
test/jwks/remote.test.mjs

A new property for the `createRemoteJWKSet` function to add a maximal TTL for the cached JWKS as discussed here:
[Cache invalidation / TTL for createRemoteJWKSet #394](https://github.com/panva/jose/discussions/394)

feat: add createRemoteJWKSet cacheMaxAge option

---

package.json

To support setting the environment in esbuild to "worker" when building for cloudflare it cannot match the worker exports. Adding the "worker" export would resolve this.
Adding a "worker" export type is logical as the cloudflare environment has the same capabilities as a "worker like webworker serviceworker.

feat: Add "worker" export in package.json

---

src/jwks/remote.ts
src/runtime/browser/fetch_jwks.ts
src/runtime/node/fetch_jwks.ts
test/jwks/remote.test.mjs

Similar to the `agent` option, this simply adds optional http headers to be sent with the fetch_wks http request.

Add optional headers for fetch_jwk

---

README.md

30.4. 2022 was yesterday, so according to README, 3.x.x and 2.x.x will not be getting bug fixes.

Update status of supported versions

---

package.json

See https://github.com/microsoft/TypeScript/issues/47792#issuecomment-1043819482
otherwise, building with nodenext resolution results in:
```
src/data-source/accessToken/jwt.ts:1:22 - error TS7016: Could not find a declaration file for module 'jose'. '/home/lizf/.yarn/berry/cache/jose-npm-4.8.0-c82ffaaa1e-9.zip/node_modules/jose/dist/node/esm/index.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/jose` if it exists or add a new declaration (.d.ts) file containing `declare module 'jose';`
1 import { jose } from "jose";
~~~~~~
```

include types export for ts4.7 nodenext resolution

---

src/jwe/flattened/decrypt.ts
src/jws/flattened/verify.ts

Move definition of protectedHeader inside try block to catch TypeError('The input to be decoded is not correctly encoded.')

Catch TypeError

---

src/key/import.ts

This PR addressed the typo mentioned in the [issue 467](https://github.com/panva/jose/issues/467)

fix: typo in importPKSC8 error message

---

docs/functions/jwk_embedded.EmbeddedJWK.md
src/jwk/embedded.ts

Updates a couple references from whitelist -> allowlist
https://developers.google.com/style/word-list#blacklist

docs: avoid non-inclusive terminology

---

docs/classes/jwt_sign.SignJWT.md
src/jwt/sign.ts

The regex replace at https://github.com/panva/jose/blob/0cd8ebafa062f8a29f6cdd9743e8c72ea04f8f0a/src/runtime/browser/asn1.ts#L174 rightly expects the "END PRIVATE KEY" to end with five "-", not four.

Add missing '-' at end of PKCS#8 key example

---

src/jws/flattened/verify.ts

When encountering a signature that cannot be decoded as base64, a type error is thrown. Ideally this should be caught and rethrown as a `JOSEError` so that error handling logic only needs to handle `JOSEError`s.

refactor: catch type error when decoding base64url signature

---

src/index.ts

GetKeyFunction type is not being re-exported to the index of types for the lib.
This is a fix for that.
Closes #591

fix(types): export GetKeyFunction

---

docs/classes/jwt_encrypt.EncryptJWT.md
docs/classes/jwt_produce.ProduceJWT.md
docs/classes/jwt_sign.SignJWT.md
docs/classes/jwt_unsecured.UnsecuredJWT.md
src/jwt/produce.ts

JSDoc like this gives me a nice idea on how to use an API and it doesn't have too much clutter imho.

docs: adds jsdocs to timestamp helpers

---

docs/jwt/decrypt/interfaces/JWTDecryptOptions.md
docs/jwt/verify/interfaces/JWTVerifyOptions.md
docs/types/interfaces/JWTClaimVerificationOptions.md
src/types.d.ts

I was a little confused about what the clockTolerance option did but the docs didn't help much, so I read the code. Here's a very minor improvement based on what I found.

docs: more details for clockTolerance on JWTVerifyOptions
